export const GET_TOKEN='GET_TOKEN';
export const REMOVE_TOKEN='REMOVE_TOKEN';
export const LOAD_USER='LOAD_USER';
export const LOAD_USER_FAIL='LOAD_USER_FAIL';
export const CLEAR_ERROR='CLEAR_ERROR';


export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_ITEMS_QUERY = 'GET_ITEMS_QUERY';
export const GET_ITEMS_QUERY_ERROR = 'GET_ITEMS_QUERY_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const CART_COUNT='CART_COUNT'
export const CART_COUNT_ERROR='CART_COUNT_ERROR'
export const GET_CART='GET_CART'
export const GET_CART_ERROR='GET_CART_ERROR'